name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v2
    - name: Setup Node
      # Setup node environment
      uses: actions/setup-node@v2
      with:
        # Node version. Run "node -v" to check the latest version
        node-version: 16.x
        registry-url: https://registry.npmjs.org/
      - name: Install project
        run: yarn install
      - name: Build the project
        run: yarn run build --if-present
      - name: Run tests
        run: yarn test
      - name: Run lint
        run: yarn lint
      - name: Run tsc
        uses: icrawl/action-tsc@v2
